### ISSUE TITLE
Buffy Questions and Challenges

### ISSUE THREAD

**Issue by lwasser** [pyOpenSci/buffy#10]
- [ ] Assign editor doesn't include message element 

why doesn't it include the custom message provided in the yaml - it does however return a template - why? the eic command should provide that template but not the editor command

```yaml
    assign_editor:
      only: editors
      add_as_assignee: true
      message: "Hey :wave: ! Let's get this review going. The editor guide can be found at https://www.pyopensci.org/software-peer-review/how-to/editors-guide.html"
      add_labels:
        - "1/editor-assigned"
      remove_labels:
        - "0/pre-review-checks"
        - "New Submission!"
```
<img width="1011" alt="Screenshot 2024-03-14 at 11 25 07 AM" src="https://github.com/pyOpenSci/test-pyos-review/assets/7649194/94c0b89d-655f-4edb-9274-1868a718d562">

- [ ] assign eic vs assign editor: why is assign eic in a basic_command section - should assign editor be a basic command to? 
    basic_command:
      - code_of_conduct:
          command: code of conduct
          description: Show our community Code of Conduct and Guidelines
          message: "Here's the pyOpenSci Community Code of Conduct: https://www.pyopensci.org/governance/CODE_OF_CONDUCT"
      - assign_eic:

- [ ] will remove editor also remove the person assigned to the issue? The reminder feature is great. but it says "authors" but it's grabbing from the reviewer field?  

```yaml
    reminders:
      only: editors
      authors:
        - author1
        - author2
```

is it possible to remind the package author (submitting author) to respond to reviews in x weeks or months too?
