### ISSUE TITLE
question: add_as_assignee param for assign_ editor not working as expected

### ISSUE THREAD

**Issue by lwasser** [pyOpenSci/buffy#19]
I have this config for assign_editor: 

```
assign_editor:
      only: editors
      add_as_assignee: true
      add_labels:
        - "1/editor-assigned"
      remove_labels:
        - "0/pre-review-checks"
        - "New Submission!"
```

* In the [docs](https://pyos-bot-buffy.readthedocs.io/en/latest/responders/assign_editor.html) it looks like add_as_assignee can be used as a param. However, when i add it, it still doesn't add the user/editor as an issue assignee it only adds them as an editor.  but i'd expect them to be added as an Assignee to the issue as well with that param set to true

* i also don't see add and remove labels as valid params an option in the docs (should i add that?)
