### ISSUE TITLE
Question about add checklist

### ISSUE THREAD

**Issue by lwasser** [pyOpenSci/buffy#21]
[This responder](https://pyos-bot-buffy.readthedocs.io/en/latest/responders/add_remove_checklist.html) seems to provide a way for us to add checklists. 

i have currently set this up so that there are [two commands associated with creating checklists](https://github.com/pyOpenSci/buffy/blob/pyopensci/config/settings-production.yml#L50)

however neither of these appear to work / appear in pyosbot help commands.

yaml looks like this now:

```yaml
    add_remove_checklist:
      - editor_response:
          only: editors
          command: editor response
          template_file: editor_response.md
          data_from_issue:
            - reviewers-list
            - author-handle
      - package_accepted:
          only: editors
          command: package accepted
          template_file: package_accepted_template.md
          data_from_issue:
            - package-name
```
i'm curious what i'm doing wrong with setting these up.

[this issue is where i'm testing things](https://github.com/pyOpenSci/test-pyos-review/issues/13)

**Comment by lwasser** [comment]
this is still an issue @xuanxu i see the commands for add checklist and there are several of them

i think by default the add checklist command adds the cnecklist to the review header. We have however a few different checklists.

1. a check list for reviewers. we normally embed that within the issue rather than adding to the header
2. A check list for kicking off the review where the duedate is included in the template .
3. a final approve check list with things to do to wrap up the review (similar to what ros has). 

Can check list be used to just add a new checklist to the issue or will it always embed the review at the top of the issue?

i looked at ros and it doesn't seem like they are embedding reviews at the top of the issue. we might need a generic add checklist element that adds a message to the issue for a specific step. but first i just want to understand if the existing responder can be customized and reused several times to post different checklists to the review. 

```
add_remove_checklist:
      - editor_response:
          only: editors
          command: editor response
          template_file: editor_response.md
          data_from_issue:
            - reviewers-list
            - author-handle
      - package_accepted:
          only: editors
          command: package accepted
          template_file: package_accepted_template.md
          data_from_issue:
            - package-name
  ```
